// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// FastSGL
Rcpp::List FastSGL(arma::mat X, arma::vec y, int numGroup, arma::vec rangeGroupInd, arma::vec groupLen, arma::vec lambdas, double alpha, int innerIter, int outerIter, double thresh, double outerThresh, double gamma, double step, int reset, int UseUPB);
RcppExport SEXP _FSGL_FastSGL(SEXP XSEXP, SEXP ySEXP, SEXP numGroupSEXP, SEXP rangeGroupIndSEXP, SEXP groupLenSEXP, SEXP lambdasSEXP, SEXP alphaSEXP, SEXP innerIterSEXP, SEXP outerIterSEXP, SEXP threshSEXP, SEXP outerThreshSEXP, SEXP gammaSEXP, SEXP stepSEXP, SEXP resetSEXP, SEXP UseUPBSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type numGroup(numGroupSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type rangeGroupInd(rangeGroupIndSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type groupLen(groupLenSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lambdas(lambdasSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type innerIter(innerIterSEXP);
    Rcpp::traits::input_parameter< int >::type outerIter(outerIterSEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    Rcpp::traits::input_parameter< double >::type outerThresh(outerThreshSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type step(stepSEXP);
    Rcpp::traits::input_parameter< int >::type reset(resetSEXP);
    Rcpp::traits::input_parameter< int >::type UseUPB(UseUPBSEXP);
    rcpp_result_gen = Rcpp::wrap(FastSGL(X, y, numGroup, rangeGroupInd, groupLen, lambdas, alpha, innerIter, outerIter, thresh, outerThresh, gamma, step, reset, UseUPB));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_FSGL_FastSGL", (DL_FUNC) &_FSGL_FastSGL, 15},
    {NULL, NULL, 0}
};

RcppExport void R_init_FSGL(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
