# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @import Rcpp
NULL

#' @useDynLib FSGL
NULL

#' @useDynLib FSGL
FastSGL <- function(X, y, numGroup, rangeGroupInd, groupLen, lambdas, alpha, innerIter, outerIter, thresh, outerThresh, gamma, step, reset, UseUPB) {
    .Call('_FSGL_FastSGL', PACKAGE = 'FSGL', X, y, numGroup, rangeGroupInd, groupLen, lambdas, alpha, innerIter, outerIter, thresh, outerThresh, gamma, step, reset, UseUPB)
}

